title: Siddhartha Borah
description: "Siddhartha Borah's personal website"
baseurl: ""
url: "https://siddharthaborah.github.io"

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections:
  essays:
    output: true
    permalink: /essay/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /post/:title/
